# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os
from dotenv import load_dotenv

class TestFormulario():
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_formulario(self):
    self.driver.get("https://virtual.um.edu.ar/login/index.php")
    self.driver.set_window_size(1680, 1025)
    load_dotenv()

    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("lm.sarmiento")
    self.driver.find_element(By.ID, "password").send_keys(os.getenv("PASSWORD"))
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.get("https://virtual.um.edu.ar/mod/questionnaire/complete.php?id=210589")
    self.driver.find_element(By.ID, "auto-rb0001").click()
    self.driver.find_element(By.ID, "dropSelecciòn").click()
    dropdown = self.driver.find_element(By.ID, "dropSelecciòn")
    dropdown.find_element(By.XPATH, "//option[. = 'Tercero']").click()
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) .ml-1 .media-body").click()